# Generated by Django 2.1 on 2019-05-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('secret', '保密')], default='保密', max_length=32, verbose_name='性别'),
        ),
    ]
